"""V0

Revision ID: a5bdbe6a47b4
Revises: 
Create Date: 2021-03-17 20:49:47.329281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bdbe6a47b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.Text(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('dt_criacao', sa.Date(), nullable=True),
    sa.Column('telefone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('senha', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.Text(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('dt_nasc', sa.Date(), nullable=True),
    sa.Column('telefone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('senha', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.Text(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('dt_nasc', sa.Date(), nullable=True),
    sa.Column('telefone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('senha', sa.Text(), nullable=True),
    sa.Column('cargo', sa.Text(), nullable=True),
    sa.Column('id_instituicao', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_instituicao'], ['instituicao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mural',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_instituicao', sa.Integer(), nullable=True),
    sa.Column('id_adm', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_adm'], ['adm.id'], ),
    sa.ForeignKeyConstraint(['id_instituicao'], ['instituicao.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal', sa.Text(), nullable=True),
    sa.Column('cor', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('dt_desaparecimento', sa.Date(), nullable=True),
    sa.Column('id_mural', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mural'], ['mural.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postagem')
    op.drop_table('mural')
    op.drop_table('adm')
    op.drop_table('usuario')
    op.drop_table('instituicao')
    # ### end Alembic commands ###
